#!/usr/bin/env bash
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RUN_ID="${RUN_ID:-$(date +%Y%m%d_%H%M%S)}"
DRY_RUN="${DRY_RUN:-1}"
PRE_CLEAN="${PRE_CLEAN:-1}"
EXEC_TIMEOUT_SECONDS="${EXEC_TIMEOUT_SECONDS:-}"
STATIC_EXEC_TIMEOUT_SECONDS="${STATIC_EXEC_TIMEOUT_SECONDS:-180}"
REMOTE_PROJECT_DIR="${REMOTE_PROJECT_DIR:-/tmp/pretrain_healthcheck_${RUN_ID}}"
MESSAGE_SIZES="${MESSAGE_SIZES:-1M}"
WARMUP="${WARMUP:-1}"
ITERS="${ITERS:-1}"
BANDWIDTH_MESSAGE_SIZES="${BANDWIDTH_MESSAGE_SIZES:-1G}"
BANDWIDTH_WARMUP="${BANDWIDTH_WARMUP:-1}"
BANDWIDTH_ITERS="${BANDWIDTH_ITERS:-3}"
BANDWIDTH_MIN_BUSBW="${BANDWIDTH_MIN_BUSBW:-0}"
BANDWIDTH_AVG_BUSBW="${BANDWIDTH_AVG_BUSBW:-0}"
COLLECTIVE_ACCEPTANCE_MESSAGE_SIZES="1K,2K,4K,8K,16K,32K,64K,128K,256K,512K,1M,2M,4M,8M,16M,32M,64M,128M,256M,512M,1G,2G"
COLLECTIVE_ACCEPTANCE_OPS="all_reduce,reduce_scatter,all_gather,broadcast,all_to_all,all_to_allv"
COLLECTIVE_BANDWIDTH_MESSAGE_SIZES="${COLLECTIVE_BANDWIDTH_MESSAGE_SIZES:-${COLLECTIVE_ACCEPTANCE_MESSAGE_SIZES}}"
COLLECTIVE_BANDWIDTH_WARMUP="${COLLECTIVE_BANDWIDTH_WARMUP:-1}"
COLLECTIVE_BANDWIDTH_ITERS="${COLLECTIVE_BANDWIDTH_ITERS:-3}"
COLLECTIVE_BANDWIDTH_MIN_BUSBW="${COLLECTIVE_BANDWIDTH_MIN_BUSBW:-0}"
COLLECTIVE_BANDWIDTH_AVG_BUSBW="${COLLECTIVE_BANDWIDTH_AVG_BUSBW:-0}"
DYNAMIC_COMPARE="${DYNAMIC_COMPARE:-1}"
DYNAMIC_KEEP_EXEC_LOGS="${DYNAMIC_KEEP_EXEC_LOGS:-0}"
EXEC_TIMEOUT_SECONDS="${EXEC_TIMEOUT_SECONDS:-180}"

run_stage() {
  local stage="$1"
  local kind="$2"
  local rc=0

  echo "[single-node-full-sync] stage=${stage} kind=${kind}"
  if [[ "${kind}" == "static" ]]; then
    RUN_ID="${RUN_ID}" RUN_STAGE="static" MODE="static" DRY_RUN="${DRY_RUN}" PRE_CLEAN="${PRE_CLEAN}" \
      STATIC_EXEC_TIMEOUT_SECONDS="${STATIC_EXEC_TIMEOUT_SECONDS}" REMOTE_PROJECT_DIR="${REMOTE_PROJECT_DIR}" \
      bash "${SCRIPT_DIR}/run_vcctl_healthcheck_with_sync.sh" || rc=$?
  else
    RUN_ID="${RUN_ID}" RUN_STAGE="${stage}" MODE="single-node" DRY_RUN="${DRY_RUN}" PRE_CLEAN="${PRE_CLEAN}" \
      EXEC_TIMEOUT_SECONDS="${EXEC_TIMEOUT_SECONDS}" DYNAMIC_COMPARE="${DYNAMIC_COMPARE}" \
      DYNAMIC_KEEP_EXEC_LOGS="${DYNAMIC_KEEP_EXEC_LOGS}" REMOTE_PROJECT_DIR="${REMOTE_PROJECT_DIR}" \
      SINGLE_NODE_CMD="cd ${REMOTE_PROJECT_DIR} && export PROJECT_REMOTE_DIR=\"${REMOTE_PROJECT_DIR}\" && STAGE_KIND=\"${kind}\" GPUS_PER_NODE=\"${GPUS_PER_NODE:-8}\" DIST_BACKEND=\"${DIST_BACKEND:-nccl}\" DEVICE_VENDOR=\"${DEVICE_VENDOR:-metax}\" COMM_RUNTIME=\"${COMM_RUNTIME:-mccl}\" DTYPE=\"${DTYPE:-bf16}\" MESSAGE_SIZES=\"${MESSAGE_SIZES}\" WARMUP=\"${WARMUP}\" ITERS=\"${ITERS}\" BANDWIDTH_MESSAGE_SIZES=\"${BANDWIDTH_MESSAGE_SIZES}\" BANDWIDTH_WARMUP=\"${BANDWIDTH_WARMUP}\" BANDWIDTH_ITERS=\"${BANDWIDTH_ITERS}\" BANDWIDTH_MIN_BUSBW=\"${BANDWIDTH_MIN_BUSBW}\" BANDWIDTH_AVG_BUSBW=\"${BANDWIDTH_AVG_BUSBW}\" COLLECTIVE_BANDWIDTH_OPS=\"${COLLECTIVE_BANDWIDTH_OPS:-${COLLECTIVE_ACCEPTANCE_OPS}}\" COLLECTIVE_BANDWIDTH_MESSAGE_SIZES=\"${COLLECTIVE_BANDWIDTH_MESSAGE_SIZES}\" COLLECTIVE_BANDWIDTH_MOE_PATTERNS=\"${COLLECTIVE_BANDWIDTH_MOE_PATTERNS:-${MOE_PATTERNS:-uniform,skewed,hot_expert,random,empty_expert}}\" COLLECTIVE_BANDWIDTH_EP_SIZE=\"${COLLECTIVE_BANDWIDTH_EP_SIZE:-8}\" COLLECTIVE_BANDWIDTH_WARMUP=\"${COLLECTIVE_BANDWIDTH_WARMUP}\" COLLECTIVE_BANDWIDTH_ITERS=\"${COLLECTIVE_BANDWIDTH_ITERS}\" COLLECTIVE_BANDWIDTH_MIN_BUSBW=\"${COLLECTIVE_BANDWIDTH_MIN_BUSBW}\" COLLECTIVE_BANDWIDTH_AVG_BUSBW=\"${COLLECTIVE_BANDWIDTH_AVG_BUSBW}\" bash scripts/metax/run_single_node_dynamic_stage.sh" \
      bash "${SCRIPT_DIR}/run_vcctl_healthcheck_with_sync.sh" || rc=$?
  fi
  return "${rc}"
}

overall_rc=0
run_stage "static" "static" || overall_rc=1
run_stage "dynamic_suite" "dynamic-suite" || overall_rc=1

echo "[single-node-full-sync] run_id=${RUN_ID}"
exit "${overall_rc}"
